### ISSUE TITLE
Why are new Threads marked as deleted for the sending user?

### ISSUE THREAD

**Issue by kamikaz1k** [tarsil/django-messages-drf#8]
hello again o/

this is more a question, so I can understand the decision process.

Why is it when you create a brand new thread, the thread (UserThread) is marked as deleted for the initiating user?
(Link to [code](https://github.com/tarsil/django-messages-drf/blob/1e30d5d7c767d83d70c076f8b5f73d7095aabb25/django_messages_drf/models.py#L193))

I was going to write a custom method to override this behaviour, but I wanted to understand if there's some underlying side effect we are trying to avoid. Because otherwise, the user is totally unaware if they have messaged someone already.

**Comment by tarsil** [comment]
Hey @kamikaz1k thank you for coming back. So, to be honest, this is the bit that came from the pinax-messages side of things but to be clear, the message is not deleted but just marked as such to avoid showing in the inbox if you send it first. So is a way of creating some sort of "sent" messages. 

I didn't change this bit as it was inspired by them but I can understand your point and I can definitely have a look or if you want, you can always open a Pull Request and provide a change as well :).

I can see you use the plugin which makes me happy as it's being useful for your projects. I will patch it in the next coming weeks with some stuff. Unfortunately because of my job, I didn't have yet the needed time to do it so.

**Comment by kamikaz1k** [comment]
Hey @tarsil I added a couple of PRs (maybe a 3rd one).

Give them a look and lmk if it is acceptable.

I am not as familiar with django app development as a library maintainer. So I don't know what's best practices for testing different configurations of the app. I made best effort, but if you have suggestions for doing things differently, feel free to suggest them.

**Comment by tarsil** [comment]
@kamikaz1k the new release is public now and I added you as one of the contributors now :)
